name: React Firebase CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Start Deploy!
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build
        env:
          VITE_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          VITE_SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}

      - name: Install Firebase Tools
        run: |
          npm install -g firebase-tools

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm install
          npm install -g firebase-tools

      - name: make FIREBASE_KEY
        # run: |
        #   echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
        #   echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 --decode > "firebase-key"

      - name: Deploy Firebase functions
        shell: bash
        run: firebase deploy --only hosting

      - name: Remove Credentials File
        if: success() || failure()
        run: |
          rm firebase-key
