name: React Firebase CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Start Deploy!

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          VITE_SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      VITE_SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_CLI_EXPERIMENTS: webframeworks

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./dist

      # - name: Prepare dist directory
      #   run: |
      #     rm -rf ./dist
      #     mkdir -p ./dist
      #     mv ./dist-artifact/* ./dist/

      - name: make FIREBASE_KEY
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

      - name: Validate Firebase Key
        run: cat ./firebase-key.json

      - name: Deploy Firebase hosting
        shell: bash
        run: firebase deploy --only hosting

      - name: Remove Credentials File
        if: success() || failure()
        run: rm firebase-key.json

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Do Jest test
        run: npn run test
